/** Hand-written mini snapshot: enough shape to exercise every tool path. */
export const fixture = {
  built: '2026-09-05',
  counts: { tools: 5, models: 2, stacks: 2, graveyard: 2 },
  tools: [
    {
      slug: 'cursor', name: 'Cursor', tagline: 'AI-first code editor with agent mode.',
      url: 'https://cursor.com', category: 'coding', pricing: 'freemium',
      price_note: 'Hobby free; Pro $20/mo', free_tier: true, open_source: false, api: false,
      self_host: false, models_used: ['claude-sonnet-5'], verdict: 'ship',
      verdict_text: 'Still the default AI editor.', strengths: ['Agent mode saves hours.'],
      use_for: ['Daily product coding in an IDE.'], skip_when: ['You need to self-host.'],
      limitations: ['Closed source.'], receipts: ['https://cursor.com/pricing'],
      last_verified: '2026-09-01', alternatives: ['claude-code', 'windsurf'], compare: [],
    },
    {
      slug: 'claude-code', name: 'Claude Code', tagline: 'Terminal coding agent from Anthropic.',
      url: 'https://claude.com/claude-code', category: 'coding', pricing: 'paid',
      price_note: 'Included with Claude Pro/Max', free_tier: false, open_source: false,
      verdict: 'ship', verdict_text: 'The terminal agent to beat.',
      use_for: ['Long autonomous coding runs.'], skip_when: ['You want a GUI editor.'],
      limitations: ['Quota burns fast.'], receipts: ['https://claude.com/claude-code'],
      last_verified: '2026-09-01', alternatives: ['cursor'], compare: [],
    },
    {
      slug: 'windsurf', name: 'Windsurf', tagline: 'Agentic IDE fork.', url: 'https://windsurf.com',
      category: 'coding', pricing: 'freemium', verdict: 'situational',
      verdict_text: 'Fine, but Cursor is ahead.', use_for: ['Teams already on it.'],
      last_verified: '2026-08-20', alternatives: ['cursor'], compare: [],
    },
    {
      slug: 'kling', name: 'Kling', tagline: 'Video generation model with strong motion.',
      url: 'https://klingai.com', category: 'video', pricing: 'freemium',
      verdict: 'ship', verdict_text: 'Best value in video generation right now.',
      use_for: ['Short video clips from a prompt.'], last_verified: '2026-08-19',
      alternatives: [], compare: [],
    },
    {
      slug: 'claude', name: 'Claude', tagline: "Anthropic's assistant, web and desktop.",
      url: 'https://claude.ai', category: 'chat', pricing: 'freemium',
      verdict: 'ship', verdict_text: 'The assistant to beat for writing and reasoning.',
      use_for: ['Long-form writing and reasoning.'], last_verified: '2026-09-01',
      alternatives: ['chatgpt'], compare: [],
    },
  ],
  models: [
    { slug: 'claude-fable-5', name: 'Claude Fable 5', provider: 'Anthropic', context_window: 1000000,
      price_input_per_mtok: 10, price_output_per_mtok: 50, open_weights: false,
      best_for: ['long-horizon autonomous agents'], avoid_for: ['cost-sensitive bulk workloads'],
      last_verified: '2026-09-01' },
    { slug: 'glm-5-3-flash', name: 'GLM 5.3 Flash', provider: 'Zhipu', context_window: 200000,
      price_input_per_mtok: 0.15, price_output_per_mtok: 0.5, open_weights: true,
      best_for: ['cheap bulk classification'], last_verified: '2026-09-01' },
  ],
  stacks: [
    { slug: 'x-content-pipeline', title: 'AI Content Pipeline for X/Twitter',
      use_case: 'Run a one-person content factory for X/Twitter.', difficulty: 'beginner',
      monthly_cost_usd: 61, tools: ['claude', 'kling'], receipts: ['https://klingai.com'],
      last_verified: '2026-08-19', budget: { monthly_cost_usd: 14, tools: ['kling'] } },
    { slug: 'solo-coding', title: 'Solo Coding Stack', use_case: 'Ship product code alone.',
      difficulty: 'intermediate', monthly_cost_usd: 40, tools: ['cursor', 'claude-code'],
      last_verified: '2026-09-01' },
  ],
  graveyard: [
    { slug: 'flowise', name: 'Flowise', url: 'https://flowiseai.com', category: 'automation',
      died: '2026-08-31', cause: 'Company wind-down — developers moved to coding agents.',
      receipt: 'https://flowiseai.com/sunset', last_verified: '2026-09-01',
      succeeded_by: { none: true, note: 'No successor.' } },
    { slug: 'roo-code', name: 'Roo Code', url: 'https://roocode.com', category: 'coding',
      died: '2026-05-15', cause: 'Team moved to Roomote.', receipt: 'https://roocode.com',
      last_verified: '2026-08-24', succeeded_by: { name: 'Roomote', url: 'https://roomote.dev' } },
  ],
};
